---
docker_repo: https://download.docker.com
# docker_repo: https://mirrors.aliyun.com/docker-ce

docker_registry_mirror: ""
# docker_registry_mirror: https://registry.docker-cn.com

docker_dns:
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
# docker_dns:
#   - 223.5.5.5
#   - 223.6.6.6
#   - 114.114.114.114

docker_log_max_size: -1
docker_log_max_file: 1
# docker_log_max_size: 100m
# docker_log_max_file: 10
